package com.ptitsa_chebupitsa.weatherapp.presentation.favorite

import com.arkivanov.decompose.ComponentContext

class DefaultFavouriteComponent(componentContext: ComponentContext): FavouriteComponent,ComponentContext by componentContext